workspace = { members = ["auth_service", "cli_utils/cat", "cli_utils/ls", "cli_utils/grep", "tmp"] }
[package]
name = "noob"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
